version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-71
    checks:
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Metrics/MethodLength:
        enabled: false
      complex-logic:
        config:
          threshold: 10
      similar-code:
        enabled: false
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
exclude_patterns:
- "tests/"
- "spec/"
- "**/*.min.css"
- "**/*.min.js"