plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-71
    checks:
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Metrics/MethodLength:
        enabled: false
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
exclude_patterns:
- "tests/"
- "spec/"