version: "2"
checks:
  complex-logic:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 250
  similar-code:
    enabled: false
plugins:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-71
  scss:
    enabled: true
exclude_patterns:
- "tests/"
- "spec/"
- "assets/**/*.min.js"
- "assets/**/*.min.css"
- "assets/javascript/purpose.*"