source 'https://rubygems.org'
ruby '2.6.3'

gem 'obscured-heartbeat', :git => 'git@github.com:gonace/Obscured.Heartbeat.git'
gem 'obscured-timeline', :git => 'git@github.com:gonace/Obscured.Timeline.git'

gem 'bcrypt'
gem 'dotenv'
gem 'geocoder'
gem 'haml'
gem 'json'
gem 'mongoid'
gem 'mongoid_search'
gem 'neatjson'
gem 'password_strength'
gem 'pony'
gem 'puma'
gem 'rack-cache'
gem 'rack-contrib'
gem 'rack-flash3'
gem 'rack-protection'
gem 'rack-user_agent'
gem 'raygun4ruby'
gem 'rest-client'
gem 'sass'
gem 'sshkit'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'slack-notifier'
gem 'sprockets'
gem 'symmetric-encryption'
gem 'uglifier'
gem 'warden'

group :test, :development do
  gem 'factory_bot'
  gem 'foreman'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'sinatra-sessionography'
  gem 'timecop'
  gem 'webmock'
end