source 'https://rubygems.org'
ruby '2.4.1'

gem 'bcrypt'
gem 'dotenv'
gem 'geocoder'
gem 'haml', '~> 5'
gem 'json'
gem 'mongoid'
gem 'password_strength'
gem 'puma'
gem 'rack-flash3'
gem 'rack-cache'
gem 'rack-contrib'
gem 'rack-user_agent'
gem 'raygun4ruby'
gem 'sass'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-param'
gem 'sinatra-partial'
gem 'sinatra-json'
gem 'slack-notifier'
gem 'pony'
gem 'platform-api'
gem 'warden'

group :test, :development do
  gem 'foreman'
  gem 'rerun' # Code reloading in dev
end