lib = File.dirname(__FILE__)
$:.unshift(lib) unless $:.include?(lib)

require 'rack/contrib/cookies'
require File.expand_path('../doorman/errors', __FILE__)
require File.expand_path('../doorman/providers/bitbucket', __FILE__)
require File.expand_path('../doorman/providers/github', __FILE__)
require File.expand_path('../doorman/strategies/password', __FILE__)
require File.expand_path('../doorman/strategies/forgot_password', __FILE__)
require File.expand_path('../doorman/strategies/remember_me', __FILE__)
require File.expand_path('../doorman/utilities/hash', __FILE__)
require File.expand_path('../doorman/utilities/roles', __FILE__)
require File.expand_path('../doorman/utilities/types', __FILE__)
require File.expand_path('../doorman/configuration', __FILE__)
require File.expand_path('../doorman/helpers', __FILE__)
require File.expand_path('../doorman/version', __FILE__)
require File.expand_path('../doorman/messages', __FILE__)
require File.expand_path('../doorman/user', __FILE__)
require File.expand_path('../doorman/base', __FILE__)