lib = File.dirname(__FILE__)
$:.unshift(lib) unless $:.include?(lib)

require 'rack/contrib/cookies'
require File.expand_path('../doorman/errors', __FILE__)
require File.expand_path('../doorman/domain/entity', __FILE__)
require File.expand_path('../doorman/domain/history', __FILE__)
require File.expand_path('../doorman/utilities/titles', __FILE__)
require File.expand_path('../doorman/utilities/roles', __FILE__)
require File.expand_path('../doorman/utilities/types', __FILE__)
require File.expand_path('../doorman/configuration', __FILE__)
require File.expand_path('../doorman/version', __FILE__)
require File.expand_path('../doorman/messages', __FILE__)
require File.expand_path('../doorman/user', __FILE__)
require File.expand_path('../doorman/base', __FILE__)